# Grab pandas to handle the dataset tables easily
import pandas as pd

# Bring in the plotting tool so we can sketch out charts later
import matplotlib.pyplot as plt

# Pull the specific tool to convert our raw text into numeric TF-IDF scores
from sklearn.feature_extraction.text import TfidfVectorizer

# Load up the cloud visualizer to turn frequent words into a graphic
from wordcloud import WordCloud

# Importing the main natural language package to clean text data
import nltk

# Grab the default list of filler words like 'the' or 'is' from NLTK
from nltk.corpus import stopwords

# Pulling strings library to quickly deal with punctuation marks
import string

# Download the actual list of English stop words to our computer
nltk.download("stopwords")

# Load up our raw BBC text dataset from its CSV file path
df = pd.read_csv("data/bbc-text.csv")

# Take a quick peek at the top 5 rows of our dataframe
df.head()

# Print out the names of the columns we have in this file
df.columns

# Turn the stop words list into a set so we can look things up faster
stop_words = set(stopwords.words("english"))

# Define a quick custom helper function to scrub our text strings clean
def clean(text):

    # Flip all characters to lowercase so capitalization doesn't break matches
    text = text.lower()

    # Strip out any exclamation points, commas, or periods from the string
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Chop the long string up into a list of separate words
    words = text.split()

    # Throw away any filler words that match our stop words list
    words = [w for w in words if w not in stop_words]

    # Glue the filtered words back together with regular blank spaces
    return " ".join(words)

# Apply our clean function down the whole text column to build a new one
df["clean_text"] = df["text"].apply(clean)

# Setup a fresh, empty vectorizer instance to count our text values
vectorizer = TfidfVectorizer()

# Feed the clean text to the model and convert it into a massive math matrix
tfidf = vectorizer.fit_transform(df["clean_text"])

# Print out the top few rows to the terminal console for a quick check
print(df.head())

# Output the column titles to make sure our clean column exists
print(df.columns)

# Log the overall size dimensions of our current dataset row by column
print(df.shape)

# Just drawing a decorative banner line for our log output formatting
print("========== PROJECT STATUS ==========")
# Display the physical grid size of our main dataframe on screen
print("Dataset Shape:", df.shape)
# Print out the columns formatted neatly as a list for readability
print("Columns:", df.columns.tolist())
# Show the matrix grid layout generated by the vectorizer tool
print("TF-IDF Matrix Shape:", tfidf.shape)
# Throw a success log message down so we know the core part finished fine
print("Program executed successfully!")

# Extract the actual text vocabulary words from our vectorizer object
feature_names = vectorizer.get_feature_names_out()

# Loop through every unique news category found in our dataset column
for category in df["category"].unique():

    # Print out a divider line to keep categories separated visually
    print("\n==============================")
    # Output the specific category name we are focusing on right now
    print("Category:", category)

    # Merge all clean text rows for this specific category into one giant text block
    category_text = " ".join(df[df["category"] == category]["clean_text"])

    # Transform our single merged text block into a TF-IDF score line
    category_tfidf = vectorizer.transform([category_text])

    # Convert the sparse matrix data back into a regular flat list of scores
    scores = category_tfidf.toarray()[0]

    # Sort the scores, grab the top 20, and reverse them to get highest first
    top_indices = scores.argsort()[-20:][::-1]

    # Look up the actual text words that match those top 20 index values
    top_words = [feature_names[i] for i in top_indices]

    # Dump the final list of top words right into our terminal screen
    print(top_words)

# Import the base OS module to manage folders on our computer
import os

# Create an images folder to save charts, and don't crash if it exists
os.makedirs("images", exist_ok=True)

# Loop over each distinct topic type again to make the clouds
for category in df["category"].unique():

    # Combine all the relevant clean text for the current topic category
    category_text = " ".join(df[df["category"] == category]["clean_text"])

    # Build the image template with specific dimensions and color theme
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color="white"
    ).generate(category_text) # Dump our text block inside to spawn the graphic

    # Define a custom filename string path using the current category label
    filename = f"images/{category}.png"

    # Export the completed word cloud graphic directly to our folder path
    wordcloud.to_file(filename)

    # Print a status note to tracking exactly what file got saved where
    print(f"Saved {filename}")


# Grab numpy for quick numerical matrix handling when setting up graph values
import numpy as np

# Start another loop to build a bar chart for every topic type
for category in df["category"].unique():

    # Collect all the cleaned text belonging to this specific news branch
    category_text = " ".join(df[df["category"] == category]["clean_text"])

    # Calculate the importance weights of the words for just this topic block
    category_tfidf = vectorizer.transform([category_text])

    # Pull out the raw numerical scores list for the current topic run
    scores = category_tfidf.toarray()[0]

    # Grab the index numbers for just the top 10 highest-scoring words
    top_indices = scores.argsort()[-10:][::-1]

    # Translate those top 10 index values into their actual string words
    top_words = [feature_names[i] for i in top_indices]

    # Grab the actual math weight scores for those specific top 10 words
    top_scores = [scores[i] for i in top_indices]

    # Set up a clean layout box measuring 10 inches by 5 inches
    plt.figure(figsize=(10,5))
    # Render a classic vertical bar chart matching our top words to weights
    plt.bar(top_words, top_scores)
    # Tilt the text labels on the bottom axis so they don't overlap each other
    plt.xticks(rotation=45)
    # Give the plot an explicit main title including the topic name string
    plt.title(f"Top TF-IDF Words - {category}")
    # Fix the spacing margins automatically so nothing gets cut off at edges
    plt.tight_layout()

    # Save the finished chart diagram image directly into our target folder
    plt.savefig(f"images/{category}_graph.png")
    # Clear out the plotting memory cache so the next chart starts fresh
    plt.close()

# Print out a quick newline and header text for our final summary list
print("\nCategories Present:")
# Show the full list of distinct group names found inside the dataframe
print(df["category"].unique())
